"""unique user_id constraint

Revision ID: dcb0cc3b9e77
Revises: a1d54cded41b
Create Date: 2023-07-22 11:20:06.069542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb0cc3b9e77'
down_revision = 'a1d54cded41b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pomodoro_setting_user_id', table_name='pomodoro_setting')
    op.create_index(op.f('ix_pomodoro_setting_user_id'), 'pomodoro_setting', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pomodoro_setting_user_id'), table_name='pomodoro_setting')
    op.create_index('ix_pomodoro_setting_user_id', 'pomodoro_setting', ['user_id'], unique=False)
    # ### end Alembic commands ###
