"""corrections

Revision ID: 2f032c8208b3
Revises: 3598d41add1b
Create Date: 2023-07-15 10:39:25.929825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f032c8208b3'
down_revision = '3598d41add1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_to_tag_tag_id_fkey', 'task_to_tag', type_='foreignkey')
    op.drop_constraint('task_to_tag_task_id_fkey', 'task_to_tag', type_='foreignkey')
    op.create_foreign_key(None, 'task_to_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_to_tag', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_to_tag', type_='foreignkey')
    op.drop_constraint(None, 'task_to_tag', type_='foreignkey')
    op.create_foreign_key('task_to_tag_task_id_fkey', 'task_to_tag', 'task', ['task_id'], ['id'])
    op.create_foreign_key('task_to_tag_tag_id_fkey', 'task_to_tag', 'tag', ['tag_id'], ['id'])
    # ### end Alembic commands ###
