"""change m2m

Revision ID: 3598d41add1b
Revises: b54d5c948587
Create Date: 2023-07-12 15:57:30.874103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3598d41add1b'
down_revision = 'b54d5c948587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_to_tag',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'tag_id')
    )
    op.create_index(op.f('ix_task_to_tag_tag_id'), 'task_to_tag', ['tag_id'], unique=False)
    op.create_index(op.f('ix_task_to_tag_task_id'), 'task_to_tag', ['task_id'], unique=False)
    op.drop_table('task_2_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_2_tag',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='task_2_tag_tag_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_2_tag_task_id_fkey'),
    sa.PrimaryKeyConstraint('tag_id', 'task_id', name='task_2_tag_pkey')
    )
    op.drop_index(op.f('ix_task_to_tag_task_id'), table_name='task_to_tag')
    op.drop_index(op.f('ix_task_to_tag_tag_id'), table_name='task_to_tag')
    op.drop_table('task_to_tag')
    # ### end Alembic commands ###
