"""adding base pomodoro tables

Revision ID: 2b0cd052dc22
Revises: 2f032c8208b3
Create Date: 2023-07-18 19:35:37.025387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0cd052dc22'
down_revision = '2f032c8208b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro_setting',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('long_rest', sa.Integer(), nullable=False),
    sa.Column('short_rest', sa.Integer(), nullable=False),
    sa.Column('work_time', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pomodoro_setting_user_id'), 'pomodoro_setting', ['user_id'], unique=False)
    op.create_table('pomodoro_history',
    sa.Column('pomodoro_setting_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pomodoro_setting_id'], ['pomodoro_setting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pomodoro_history_pomodoro_setting_id'), 'pomodoro_history', ['pomodoro_setting_id'], unique=False)
    op.add_column('task', sa.Column('pomodoro_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_pomodoro_id'), 'task', ['pomodoro_id'], unique=False)
    op.create_foreign_key(None, 'task', 'pomodoro_setting', ['pomodoro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_pomodoro_id'), table_name='task')
    op.drop_column('task', 'pomodoro_id')
    op.drop_index(op.f('ix_pomodoro_history_pomodoro_setting_id'), table_name='pomodoro_history')
    op.drop_table('pomodoro_history')
    op.drop_index(op.f('ix_pomodoro_setting_user_id'), table_name='pomodoro_setting')
    op.drop_table('pomodoro_setting')
    # ### end Alembic commands ###
