"""Changes in model

Revision ID: 0d038214965c
Revises: b618611a4984
Create Date: 2023-06-25 11:11:57.968586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d038214965c'
down_revision = 'b618611a4984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
