"""changing task pomodoro_id reference

Revision ID: a1d54cded41b
Revises: 2b0cd052dc22
Create Date: 2023-07-18 19:38:23.414982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d54cded41b'
down_revision = '2b0cd052dc22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
